public class MovieTest {
    public static void main(String[] args) {
        // Test file has been generated by ChatGPt o4-mini-high 2025-07-25

        // MovieManager 인스턴스 생성 - singleton 디자인 된 instance get method로 호출하기
        // MovieManagerImpl manager = new MovieManagerImpl();
        IMovieManager manager = MovieManagerImpl.getInstance();

        // // 일반 영화 2개 추가
        // Movie m1 = new Movie(1, "Inception", "Christopher Nolan", "Sci-Fi", 148);
        // Movie m2 = new Movie(2, "The Godfather", "Francis Ford Coppola", "Crime", 175);
        // manager.add(m1);
        // manager.add(m2);

        // // 시리즈 영화 2개 추가
        // SeriesMovie sm1 = new SeriesMovie(3, "Star Wars", "George Lucas", "Sci-Fi", 121, 4, "Episode IV");
        // SeriesMovie sm2 = new SeriesMovie(4, "Star Wars", "George Lucas", "Sci-Fi", 124, 5, "Episode V");
        // manager.add(sm1);
        // manager.add(sm2);

        // manager.saveData();

        // 전체 영화 목록 출력
        System.out.println("=== All Movies ===");
        for (Movie m : manager.getList()) {
            System.out.println(m);
        }

        // 제목에 "Star"가 포함된 영화 검색
        System.out.println("\n=== Search by title 'Star' ===");
        try {
            Movie[] found = manager.searchByTitle("Star");
            for (Movie m : found) {
                System.out.println(m);
            }
        } catch (TitleNotFoundException e) {
            System.out.println("예외 발생: " + e.getMessage());
        }

        // 존재하지 않는 영화 검색 테스트
        System.out.println("\n=== Search by title 'Avatar' (Not Registered) ===");
        try {
            Movie[] notFound = manager.searchByTitle("Avatar");
            for (Movie m : notFound) {
                System.out.println(m);
            }
        } catch (TitleNotFoundException e) {
            System.out.println("예외 발생: " + e.getMessage());
        }

        // 시리즈 영화만 출력
        System.out.println("\n=== Series Movies ===");
        for (SeriesMovie sm : manager.getSeriesMovies()) {
            System.out.println(sm);
        }

        // 평균 러닝타임 계산 및 출력
        System.out.println("\n=== Average Running Time ===");
        System.out.println(manager.getRunningTimeAvg());
    }

}
